name: C++ CI with Ubuntu Latest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc-11 g++-11 make
        
        # Set GCC 11 as default
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 100
        
        # Verify GCC version
        gcc --version
        g++ --version
      shell: bash

    - name: Cache build artifacts
      uses: actions/cache@v3
      with:
        path: |
          stream_buffer/build
        key: ${{ runner.os }}-build-${{ hashFiles('stream_buffer/**/*.cpp', 'stream_buffer/**/*.h', 'stream_buffer/Makefile') }}
        restore-keys: |
          ${{ runner.os }}-build-

    - name: Check C++11 compatibility
      run: |
        cd stream_buffer
        make cpp11-check
      shell: bash

    - name: Build
      run: |
        cd stream_buffer
        make clean # Ensure clean build
        make all
      shell: bash

    - name: Run tests
      run: |
        cd stream_buffer
        make test
      shell: bash
      
  static-analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install cppcheck and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cppcheck
      
    - name: Run cppcheck
      run: |
        cppcheck --enable=all --suppress=missingIncludeSystem --error-exitcode=1 -I stream_buffer/include --suppress=unusedFunction stream_buffer/
        
    - name: Install additional static analyzers
      continue-on-error: true
      run: |
        sudo apt-get install -y clang-tools || echo "clang-tools not available, skipping"
      
  code-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc-11 g++-11 make lcov
        
        # Set GCC 11 as default
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 100
      shell: bash
    
    - name: Build with coverage
      run: |
        cd stream_buffer
        make clean # Ensure clean build for accurate coverage
        make debug CXXFLAGS="-std=c++11 -Wall -Wextra -Wpedantic -O0 -g --coverage -pthread"
      shell: bash
    
    - name: Run tests with coverage
      run: |
        cd stream_buffer
        make test CXXFLAGS="-std=c++11 -Wall -Wextra -Wpedantic -O0 -g --coverage -pthread"
      shell: bash

    - name: Generate coverage report
      run: |
        cd stream_buffer
        lcov --directory . --capture --output-file coverage.info
        lcov --remove coverage.info '/usr/*' --output-file coverage.info
        lcov --list coverage.info
      shell: bash
      
    - name: Archive coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: stream_buffer/coverage.info
